Updates Home Repository URL
ditkrg/outboxable pull request #2
Opened 2023-03-06 11:55 UTC by muhammadnawzad

2023-03-06 13:44 UTC, muhammadnawzad commented
There are still some errors with rubocop using an old ruby parser that doesn't recognize the syntax `attribute:`

2023-03-06 22:18 UTC, broosk1993 requested changes

2023-03-06 22:18 UTC, broosk1993 commented on Gemfile
> +gem 'sidekiq-cron', '~> 1.9'
Unnecessary. The Gem will not run if the project which uses the Gem does not have sidekiq-cron. Better to delegate the management of these gems to the parent project as they may not be desired

2023-03-06 22:18 UTC, broosk1993 commented on Gemfile
> +gem 'activesupport', '~> 7.0.4.2'
The gem also does not work if the application that uses it is not a Rails app. So the inclusion of ActiveSupport is not only undesired, it will also lead to conflict for later version of Rails.

2023-03-06 22:18 UTC, broosk1993 commented on lib/outboxable.rb
> +require 'active_support'
No need

2023-03-06 22:18 UTC, broosk1993 commented on lib/outboxable/worker.rb
> +require 'sidekiq'
No need.

2023-03-12 07:41 UTC, arikarim commented
@muhammadnawzad  please change `RABBITMQ__USER` variable to `RABBITMQ__USERNAME`.

2023-03-12 14:48 UTC, broosk1993 approved these changes

2023-03-12 14:48 UTC, broosk1993 commented on Gemfile.lock
>  GEM
Re run bundle @muhammadnawzad

2023-03-12 14:48 UTC, merged